from unittest.mock import patch

from calculations import scout_precision
import server


class TestScoutPrecisionCalc:
    def setup_method(self):
        self.tba_test_data = [
            {
                "match_number": 1,
                "actual_time": 1100291640,
                "comp_level": "qm",
                "score_breakdown": {
                    "blue": {
                        "foulPoints": 8,
                        "autoLeavePoints": 15,
                        "totalPoints": 87,
                        "endgamePoints": 6,
                    },
                    "red": {
                        "foulPoints": 10,
                        "autoLeavePoints": 0,
                        "totalPoints": 159,
                        "endgamePoints": 15,
                    },
                },
            },
            {
                "match_number": 2,
                "actual_time": 1087511040,
                "comp_level": "qm",
                "score_breakdown": {
                    "blue": {
                        "foulPoints": 0,
                        "autoLeavePoints": 0,
                        "totalPoints": 149,
                        "endgamePoints": 25,
                    },
                    "red": {
                        "foulPoints": 10,
                        "autoLeavePoints": 0,
                        "totalPoints": 98,
                        "endgamePoints": 4,
                    },
                },
            },
            {
                "match_number": 3,
                "actual_time": None,
                "comp_level": "qm",
                "score_breakdown": None,
            },
        ]
        self.scout_tim_test_data = [
            # Match 1
            {
                "scout_name": "ALISON LIN",
                "team_number": "1678",
                "match_number": 1,
                "alliance_color_is_red": True,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 0,
                "auto_coral_L3": 0,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 0,
                "tele_coral_L2": 1,
                "tele_coral_L3": 1,
                "tele_coral_L4": 0,
            },
            {
                "scout_name": "NATHAN MILLS",
                "team_number": "1678",
                "match_number": 1,
                "alliance_color_is_red": True,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 0,
                "auto_coral_L3": 0,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 0,
                "tele_coral_L2": 0,
                "tele_coral_L3": 20,
                "tele_coral_L4": 1,
            },
            {
                "scout_name": "KATHY LI",
                "team_number": "4414",
                "match_number": 1,
                "alliance_color_is_red": True,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 0,
                "auto_coral_L3": 0,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 0,
                "tele_coral_L2": 1,
                "tele_coral_L3": 15,
                "tele_coral_L4": 0,
            },
            {
                "scout_name": "SCOTT WOOLLEY",
                "team_number": "589",
                "match_number": 1,
                "alliance_color_is_red": True,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 0,
                "auto_coral_L3": 0,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 15,
                "tele_coral_L2": 1,
                "tele_coral_L3": 1,
                "tele_coral_L4": 0,
            },
            {
                "scout_name": "JELLIFER KENT",
                "team_number": "589",
                "match_number": 1,
                "alliance_color_is_red": True,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 0,
                "auto_coral_L3": 14,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 0,
                "tele_coral_L2": 1,
                "tele_coral_L3": 1,
                "tele_coral_L4": 0,
            },
            {
                "scout_name": "ALISON YOUNG",
                "team_number": "589",
                "match_number": 1,
                "alliance_color_is_red": True,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 0,
                "auto_coral_L3": 0,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 11,
                "tele_coral_L2": 1,
                "tele_coral_L3": 1,
                "tele_coral_L4": 0,
            },
            # Match 2
            {
                "scout_name": "NATHAN MILLS",
                "team_number": "1678",
                "match_number": 2,
                "alliance_color_is_red": False,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 1,
                "auto_coral_L3": 0,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 0,
                "tele_coral_L2": 1,
                "tele_coral_L3": 1,
                "tele_coral_L4": 0,
            },
            {
                "scout_name": "KATHY LI",
                "team_number": "4414",
                "match_number": 2,
                "alliance_color_is_red": False,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 1,
                "auto_coral_L3": 0,
                "auto_coral_L4": 1,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 0,
                "tele_coral_L2": 1,
                "tele_coral_L3": 1,
                "tele_coral_L4": 0,
            },
            {
                "scout_name": "AMY SHAN",
                "team_number": "589",
                "match_number": 2,
                "alliance_color_is_red": False,
                "auto_net": 0,
                "auto_processor": 1,
                "auto_coral_L1": 1,
                "auto_coral_L2": 0,
                "auto_coral_L3": 0,
                "auto_coral_L4": 2,
                "tele_net": 1,
                "tele_processor": 0,
                "tele_coral_L1": 0,
                "tele_coral_L2": 1,
                "tele_coral_L3": 1,
                "tele_coral_L4": 0,
            },
        ]

        with patch("doozernet_communicator.check_model_availability", return_value=None):
            self.test_server = server.Server()
        self.test_calc = scout_precision.ScoutPrecisionCalc(self.test_server)

    def test___init__(self):
        assert self.test_calc.watched_collections == ["unconsolidated_totals"]
        assert self.test_calc.server == self.test_server

    def test_calc_scout_precision(self):
        assert not self.test_calc.calc_scout_precision([{"scout_name": "REED WANG"}])
        test_data = [
            {
                "scout_name": "JELLIFER KENT",
                "match_number": 1,
                "sim_precision": 19,
                "auto_reef_precision": 5,
                "auto_L1_precision": 9,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 0,
                "auto_F3_L2_precision": 0,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 12,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 0,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 21,
                "auto_F1_L4_precision": 7,
                "auto_F2_L4_precision": 0,
                "auto_F3_L4_precision": 0,
                "auto_F4_L4_precision": 7,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 7,
                "tele_reef_precision": 31,
                "algae_precision": 0,
                "net_precision": 0,
                "processor_precision": 0,
            },
            {
                "scout_name": "JELLIFER KENT",
                "match_number": 2,
                "sim_precision": 19,
                "auto_reef_precision": 5,
                "auto_L1_precision": 9,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 0,
                "auto_F3_L2_precision": 0,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 12,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 0,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 21,
                "auto_F1_L4_precision": 7,
                "auto_F2_L4_precision": 0,
                "auto_F3_L4_precision": 0,
                "auto_F4_L4_precision": 7,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 7,
                "tele_reef_precision": 31,
                "algae_precision": 0,
                "net_precision": 0,
                "processor_precision": 0,
            },
            {
                "scout_name": "JELLIFER KENT",
                "match_number": 3,
                "sim_precision": 2,
                "auto_reef_precision": 3,
                "auto_L1_precision": 8,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 0,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 0,
                "auto_F2_L4_precision": 0,
                "auto_F3_L4_precision": 0,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 15,
                "algae_precision": 6,
                "net_precision": 4,
                "processor_precision": 6,
            },
            {
                "scout_name": "JELLIFER KENT",
                "match_number": 4,
                "sim_precision": 5,
                "auto_reef_precision": 6,
                "auto_L1_precision": 8,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 2,
                "auto_F2_L3_precision": 3,
                "auto_F3_L3_precision": 2,
                "auto_F4_L3_precision": 2,
                "auto_F5_L3_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 0,
                "auto_F2_L4_precision": 6,
                "auto_F3_L4_precision": 6,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 1,
                "algae_precision": 0,
                "net_precision": 4,
                "processor_precision": 6,
            },
            {
                "scout_name": "JELLIFER KENT",
                "match_number": 5,
                "sim_precision": 0.1,
                "auto_reef_precision": 2,
                "auto_L1_precision": 2,
                "auto_L2_precision": 2,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 3,
                "auto_F5_L2_precision": 3,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 9,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 9,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 0,
                "auto_F2_L4_precision": 4,
                "auto_F3_L4_precision": 4,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 15,
                "algae_precision": 6,
                "net_precision": 4,
                "processor_precision": 6,
            },
        ]
        assert self.test_calc.calc_scout_precision(test_data) == {
            "algae_precision": 2.4,
            "auto_F1_L2_precision": 4.0,
            "auto_F1_L3_precision": 6.8,
            "auto_F1_L4_precision": 2.8,
            "auto_F2_L2_precision": 0.6,
            "auto_F2_L3_precision": 2.4,
            "auto_F2_L4_precision": 2.0,
            "auto_F3_L2_precision": 0.6,
            "auto_F3_L3_precision": 5.2,
            "auto_F3_L4_precision": 2.0,
            "auto_F4_L2_precision": 3.8,
            "auto_F4_L3_precision": 5.2,
            "auto_F4_L4_precision": 2.8,
            "auto_F5_L2_precision": 3.8,
            "auto_F5_L3_precision": 2.2,
            "auto_F5_L4_precision": 0.0,
            "auto_F6_L2_precision": 2.0,
            "auto_F6_L3_precision": 0.0,
            "auto_F6_L4_precision": 2.8,
            "auto_L1_precision": 7.2,
            "auto_L2_precision": 4.4,
            "auto_L3_precision": 7.2,
            "auto_L4_precision": 8.4,
            "auto_reef_precision": 4.2,
            "net_precision": 2.4,
            "processor_precision": 3.6,
            "scout_precision": 9.02,
            "tele_reef_precision": 18.6,
        }

    def test_calc_ranks(self):
        test_data = [
            {
                "scout_name": "ALISON YOUNG",
                "scout_precision": 0,
            },
            {
                "scout_name": "KATHY LI",
                "scout_precision": 3.61111111111111,
            },
            {
                "scout_name": "AMY SHAN",
                "scout_precision": 100,
            },
            {
                "scout_name": "ALISON LIN",
                "scout_precision": 8.222222222222221,
            },
            {
                "scout_name": "SCOTT WOOLLEY",
            },
        ]
        expected_output = [
            {
                "scout_name": "ALISON YOUNG",
                "scout_precision": 0,
                "scout_precision_rank": 1,
            },
            {
                "scout_name": "KATHY LI",
                "scout_precision": 3.61111111111111,
                "scout_precision_rank": 2,
            },
            {
                "scout_name": "ALISON LIN",
                "scout_precision": 8.222222222222221,
                "scout_precision_rank": 3,
            },
            {
                "scout_name": "AMY SHAN",
                "scout_precision": 100,
                "scout_precision_rank": 4,
            },
            {
                "scout_name": "SCOTT WOOLLEY",
                "scout_precision_rank": 5,
            },
        ]
        assert self.test_calc.calc_ranks(test_data) == expected_output

    def test_update_scout_precision_calcs(self):
        with patch(
            "calculations.scout_precision.ScoutPrecisionCalc.calc_scout_precision",
            return_value={
                "algae_precision": 2.4,
                "auto_F1_L2_precision": 4.0,
                "auto_F1_L3_precision": 6.8,
                "auto_F1_L4_precision": 2.8,
                "auto_F2_L2_precision": 0.6,
                "auto_F2_L3_precision": 2.4,
                "auto_F2_L4_precision": 2.0,
                "auto_F3_L2_precision": 0.6,
                "auto_F3_L3_precision": 5.2,
                "auto_F3_L4_precision": 2.0,
                "auto_F4_L2_precision": 3.8,
                "auto_F4_L3_precision": 5.2,
                "auto_F4_L4_precision": 2.8,
                "auto_F5_L2_precision": 3.8,
                "auto_F5_L3_precision": 2.2,
                "auto_F5_L4_precision": 0.0,
                "auto_F6_L2_precision": 2.0,
                "auto_F6_L3_precision": 0.0,
                "auto_F6_L4_precision": 2.8,
                "auto_L1_precision": 7.2,
                "auto_L2_precision": 4.4,
                "auto_L3_precision": 7.2,
                "auto_L4_precision": 8.4,
                "auto_reef_precision": 4.2,
                "net_precision": 2.4,
                "processor_precision": 3.6,
                "scout_precision": 9.02,
                "tele_reef_precision": 18.6,
            },
        ):
            assert self.test_calc.update_scout_precision_calcs(["REED WANG"]) == [
                {
                    "scout_name": "REED WANG",
                    "scout_precision": 9.02,
                    "scout_precision_rank": 1,
                    "algae_precision": 2.4,
                    "auto_F1_L2_precision": 4.0,
                    "auto_F1_L3_precision": 6.8,
                    "auto_F1_L4_precision": 2.8,
                    "auto_F2_L2_precision": 0.6,
                    "auto_F2_L3_precision": 2.4,
                    "auto_F2_L4_precision": 2.0,
                    "auto_F3_L2_precision": 0.6,
                    "auto_F3_L3_precision": 5.2,
                    "auto_F3_L4_precision": 2.0,
                    "auto_F4_L2_precision": 3.8,
                    "auto_F4_L3_precision": 5.2,
                    "auto_F4_L4_precision": 2.8,
                    "auto_F5_L2_precision": 3.8,
                    "auto_F5_L3_precision": 2.2,
                    "auto_F5_L4_precision": 0.0,
                    "auto_F6_L2_precision": 2.0,
                    "auto_F6_L3_precision": 0.0,
                    "auto_F6_L4_precision": 2.8,
                    "auto_L1_precision": 7.2,
                    "auto_L2_precision": 4.4,
                    "auto_L3_precision": 7.2,
                    "auto_L4_precision": 8.4,
                    "auto_reef_precision": 4.2,
                    "net_precision": 2.4,
                    "processor_precision": 3.6,
                    "tele_reef_precision": 18.6,
                }
            ]

    def test_run(self):

        scout_precision_data = [
            {
                "scout_name": "JELLIFER KENT",
                "scout_precision": 8,
                "auto_reef_precision": 5,
                "auto_L1_precision": 9,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 0,
                "auto_F3_L2_precision": 0,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 12,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 0,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 21,
                "auto_F1_L4_precision": 7,
                "auto_F2_L4_precision": 0,
                "auto_F3_L4_precision": 0,
                "auto_F4_L4_precision": 7,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 7,
                "tele_reef_precision": 31,
                "algae_precision": 0,
                "net_precision": 0,
                "processor_precision": 0,
            },
            {
                "scout_name": "SCOTT WOOLLEY",
                "scout_precision": 9,
                "auto_reef_precision": 5,
                "auto_L1_precision": 9,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 0,
                "auto_F3_L2_precision": 0,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 12,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 0,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 21,
                "auto_F1_L4_precision": 7,
                "auto_F2_L4_precision": 0,
                "auto_F3_L4_precision": 0,
                "auto_F4_L4_precision": 7,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 7,
                "tele_reef_precision": 31,
                "algae_precision": 0,
                "net_precision": 0,
                "processor_precision": 0,
            },
            {
                "scout_name": "ALISON YOUNG",
                "scout_precision": 0.01,
                "auto_reef_precision": 3,
                "auto_L1_precision": 8,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 0,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 0,
                "auto_F2_L4_precision": 0,
                "auto_F3_L4_precision": 0,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 15,
                "algae_precision": 6,
                "net_precision": 4,
                "processor_precision": 6,
            },
            {
                "scout_name": "AMY SHAN",
                "scout_precision": 4,
                "auto_reef_precision": 6,
                "auto_L1_precision": 8,
                "auto_L2_precision": 5,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 4,
                "auto_F5_L2_precision": 4,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 2,
                "auto_F2_L3_precision": 3,
                "auto_F3_L3_precision": 2,
                "auto_F4_L3_precision": 2,
                "auto_F5_L3_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 0,
                "auto_F2_L4_precision": 6,
                "auto_F3_L4_precision": 6,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 1,
                "algae_precision": 0,
                "net_precision": 4,
                "processor_precision": 6,
            },
            {
                "scout_name": "SARAH O-H",
                "scout_precision": 0.1,
                "auto_reef_precision": 2,
                "auto_L1_precision": 2,
                "auto_L2_precision": 2,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 3,
                "auto_F5_L2_precision": 3,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F2_L3_precision": 9,
                "auto_F3_L3_precision": 6,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 9,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 0,
                "auto_F2_L4_precision": 4,
                "auto_F3_L4_precision": 4,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 15,
                "algae_precision": 6,
                "net_precision": 4,
                "processor_precision": 6,
            },
            {
                "scout_name": "ANDY ZHANG",
                "scout_precision": 100,
                "auto_reef_precision": 2,
                "auto_L1_precision": 2,
                "auto_L2_precision": 2,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 3,
                "auto_F5_L2_precision": 3,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 5,
                "auto_F2_L3_precision": 5,
                "auto_F3_L3_precision": 5,
                "auto_F4_L3_precision": 6,
                "auto_F5_L3_precision": 9,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 0,
                "auto_F2_L4_precision": 4,
                "auto_F3_L4_precision": 4,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 8,
                "algae_precision": 6,
                "net_precision": 4,
                "processor_precision": 6,
            },
            {
                "scout_name": "CYAN DING",
                "scout_precision": 101,
                "auto_reef_precision": 6,
                "auto_L1_precision": 6,
                "auto_L2_precision": 2,
                "auto_F1_L2_precision": 4,
                "auto_F2_L2_precision": 1,
                "auto_F3_L2_precision": 1,
                "auto_F4_L2_precision": 8,
                "auto_F5_L2_precision": 8,
                "auto_F6_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_F1_L3_precision": 5,
                "auto_F2_L3_precision": 1,
                "auto_F3_L3_precision": 1,
                "auto_F4_L3_precision": 1,
                "auto_F5_L3_precision": 9,
                "auto_F6_L3_precision": 0,
                "auto_L4_precision": 0,
                "auto_F1_L4_precision": 2,
                "auto_F2_L4_precision": 2,
                "auto_F3_L4_precision": 2,
                "auto_F4_L4_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L4_precision": 0,
                "tele_reef_precision": 8,
                "algae_precision": 6,
                "net_precision": 4,
                "processor_precision": 2,
            },
        ]

        expected_scout_precision = [
            {
                "scout_name": "ALISON YOUNG",
                "algae_precision": 6,
                "auto_F1_L2_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F1_L4_precision": 0,
                "auto_F2_L2_precision": 1,
                "auto_F2_L3_precision": 0,
                "auto_F2_L4_precision": 0,
                "auto_F3_L2_precision": 1,
                "auto_F3_L3_precision": 6,
                "auto_F3_L4_precision": 0,
                "auto_F4_L2_precision": 4,
                "auto_F4_L3_precision": 6,
                "auto_F4_L4_precision": 0,
                "auto_F5_L2_precision": 4,
                "auto_F5_L3_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L2_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_F6_L4_precision": 0,
                "auto_L1_precision": 8,
                "auto_L2_precision": 5,
                "auto_L3_precision": 4,
                "auto_L4_precision": 0,
                "auto_reef_precision": 3,
                "net_precision": 4,
                "processor_precision": 6,
                "scout_precision": 0.01,
                "scout_precision_rank": 1,
                "tele_reef_precision": 15,
            },
            {
                "scout_name": "SARAH O-H",
                "algae_precision": 6,
                "auto_F1_L2_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F1_L4_precision": 0,
                "auto_F2_L2_precision": 1,
                "auto_F2_L3_precision": 9,
                "auto_F2_L4_precision": 4,
                "auto_F3_L2_precision": 1,
                "auto_F3_L3_precision": 6,
                "auto_F3_L4_precision": 4,
                "auto_F4_L2_precision": 3,
                "auto_F4_L3_precision": 6,
                "auto_F4_L4_precision": 0,
                "auto_F5_L2_precision": 3,
                "auto_F5_L3_precision": 9,
                "auto_F5_L4_precision": 0,
                "auto_F6_L2_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_F6_L4_precision": 0,
                "auto_L1_precision": 2,
                "auto_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_L4_precision": 0,
                "auto_reef_precision": 2,
                "net_precision": 4,
                "processor_precision": 6,
                "scout_precision": 0.1,
                "scout_precision_rank": 2,
                "tele_reef_precision": 15,
            },
            {
                "scout_name": "AMY SHAN",
                "algae_precision": 0,
                "auto_F1_L2_precision": 4,
                "auto_F1_L3_precision": 2,
                "auto_F1_L4_precision": 0,
                "auto_F2_L2_precision": 1,
                "auto_F2_L3_precision": 3,
                "auto_F2_L4_precision": 6,
                "auto_F3_L2_precision": 1,
                "auto_F3_L3_precision": 2,
                "auto_F3_L4_precision": 6,
                "auto_F4_L2_precision": 4,
                "auto_F4_L3_precision": 2,
                "auto_F4_L4_precision": 0,
                "auto_F5_L2_precision": 4,
                "auto_F5_L3_precision": 2,
                "auto_F5_L4_precision": 0,
                "auto_F6_L2_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_F6_L4_precision": 0,
                "auto_L1_precision": 8,
                "auto_L2_precision": 5,
                "auto_L3_precision": 4,
                "auto_L4_precision": 0,
                "auto_reef_precision": 6,
                "net_precision": 4,
                "processor_precision": 6,
                "scout_precision": 4,
                "scout_precision_rank": 3,
                "tele_reef_precision": 1,
            },
            {
                "scout_name": "JELLIFER KENT",
                "algae_precision": 0,
                "auto_F1_L2_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F1_L4_precision": 7,
                "auto_F2_L2_precision": 0,
                "auto_F2_L3_precision": 0,
                "auto_F2_L4_precision": 0,
                "auto_F3_L2_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F3_L4_precision": 0,
                "auto_F4_L2_precision": 4,
                "auto_F4_L3_precision": 6,
                "auto_F4_L4_precision": 7,
                "auto_F5_L2_precision": 4,
                "auto_F5_L3_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L2_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_F6_L4_precision": 7,
                "auto_L1_precision": 9,
                "auto_L2_precision": 5,
                "auto_L3_precision": 12,
                "auto_L4_precision": 21,
                "auto_reef_precision": 5,
                "net_precision": 0,
                "processor_precision": 0,
                "scout_precision": 8,
                "scout_precision_rank": 4,
                "tele_reef_precision": 31,
            },
            {
                "scout_name": "SCOTT WOOLLEY",
                "algae_precision": 0,
                "auto_F1_L2_precision": 4,
                "auto_F1_L3_precision": 8,
                "auto_F1_L4_precision": 7,
                "auto_F2_L2_precision": 0,
                "auto_F2_L3_precision": 0,
                "auto_F2_L4_precision": 0,
                "auto_F3_L2_precision": 0,
                "auto_F3_L3_precision": 6,
                "auto_F3_L4_precision": 0,
                "auto_F4_L2_precision": 4,
                "auto_F4_L3_precision": 6,
                "auto_F4_L4_precision": 7,
                "auto_F5_L2_precision": 4,
                "auto_F5_L3_precision": 0,
                "auto_F5_L4_precision": 0,
                "auto_F6_L2_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_F6_L4_precision": 7,
                "auto_L1_precision": 9,
                "auto_L2_precision": 5,
                "auto_L3_precision": 12,
                "auto_L4_precision": 21,
                "auto_reef_precision": 5,
                "net_precision": 0,
                "processor_precision": 0,
                "scout_precision": 9,
                "scout_precision_rank": 5,
                "tele_reef_precision": 31,
            },
            {
                "scout_name": "ANDY ZHANG",
                "algae_precision": 6,
                "auto_F1_L2_precision": 4,
                "auto_F1_L3_precision": 5,
                "auto_F1_L4_precision": 0,
                "auto_F2_L2_precision": 1,
                "auto_F2_L3_precision": 5,
                "auto_F2_L4_precision": 4,
                "auto_F3_L2_precision": 1,
                "auto_F3_L3_precision": 5,
                "auto_F3_L4_precision": 4,
                "auto_F4_L2_precision": 3,
                "auto_F4_L3_precision": 6,
                "auto_F4_L4_precision": 0,
                "auto_F5_L2_precision": 3,
                "auto_F5_L3_precision": 9,
                "auto_F5_L4_precision": 0,
                "auto_F6_L2_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_F6_L4_precision": 0,
                "auto_L1_precision": 2,
                "auto_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_L4_precision": 0,
                "auto_reef_precision": 2,
                "net_precision": 4,
                "processor_precision": 6,
                "scout_precision": 100,
                "scout_precision_rank": 6,
                "tele_reef_precision": 8,
            },
            {
                "scout_name": "CYAN DING",
                "algae_precision": 6,
                "auto_F1_L2_precision": 4,
                "auto_F1_L3_precision": 5,
                "auto_F1_L4_precision": 2,
                "auto_F2_L2_precision": 1,
                "auto_F2_L3_precision": 1,
                "auto_F2_L4_precision": 2,
                "auto_F3_L2_precision": 1,
                "auto_F3_L3_precision": 1,
                "auto_F3_L4_precision": 2,
                "auto_F4_L2_precision": 8,
                "auto_F4_L3_precision": 1,
                "auto_F4_L4_precision": 0,
                "auto_F5_L2_precision": 8,
                "auto_F5_L3_precision": 9,
                "auto_F5_L4_precision": 0,
                "auto_F6_L2_precision": 2,
                "auto_F6_L3_precision": 0,
                "auto_F6_L4_precision": 0,
                "auto_L1_precision": 6,
                "auto_L2_precision": 2,
                "auto_L3_precision": 4,
                "auto_L4_precision": 0,
                "auto_reef_precision": 6,
                "net_precision": 4,
                "processor_precision": 2,
                "scout_precision": 101,
                "scout_precision_rank": 7,
                "tele_reef_precision": 8,
            },
        ]
        self.test_server.local_db.delete_data("unconsolidated_totals")
        self.test_server.local_db.insert_documents(
            "unconsolidated_totals", self.scout_tim_test_data
        )
        with patch(
            "calculations.scout_precision.ScoutPrecisionCalc.calc_scout_precision",
            side_effect=scout_precision_data,
        ):
            with patch(
                "tba_communicator.tba_request",
                return_value=self.tba_test_data,
            ):
                self.test_calc.run()
        scout_precision_result = self.test_server.local_db.find("scout_precision")
        for document in scout_precision_result:
            document.pop("_id")
            assert document in expected_scout_precision
