from calculations import predicted_elims
from unittest.mock import patch
from calculations import predicted_aim
import server


class TestPredictedElimsCalc:
    def setup_method(self):
        with patch("doozernet_communicator.check_model_availability", return_value=None):
            self.test_server = server.Server()
        self.tba_playoffs_data = [
            {
                "name": "Alliance 1",
                "decines": [],
                "picks": ["frc1678", "frc254", "frc4414"],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 0, "wins": 0, "ties": 1},
                    "status": "won",
                },
            },
            {
                "name": "Alliance 2",
                "decines": [],
                "picks": [
                    "frc1323",
                    "frc125",
                    "frc5940",
                ],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 2, "wins": 6, "ties": 1},
                    "status": "won",
                },
            },
            {
                "name": "Alliance 3",
                "decines": [],
                "picks": ["frc1323", "frc254", "frc4414"],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 2, "wins": 6, "ties": 1},
                    "status": "won",
                },
            },
            {
                "name": "Alliance 4",
                "decines": [],
                "picks": [
                    "frc1678",
                    "frc125",
                    "frc5940",
                ],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 2, "wins": 6, "ties": 1},
                    "status": "won",
                },
            },
            {
                "name": "Alliance 5",
                "decines": [],
                "picks": ["frc1678", "frc125", "frc4414"],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 2, "wins": 6, "ties": 1},
                    "status": "won",
                },
            },
            {
                "name": "Alliance 6",
                "decines": [],
                "picks": [
                    "frc1323",
                    "frc254",
                    "frc5940",
                ],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 2, "wins": 6, "ties": 1},
                    "status": "won",
                },
            },
            {
                "name": "Alliance 7",
                "decines": [],
                "picks": ["frc1678", "frc125", "frc5940"],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 2, "wins": 6, "ties": 1},
                    "status": "won",
                },
            },
            {
                "name": "Alliance 8",
                "decines": [],
                "picks": [
                    "frc1323",
                    "frc125",
                    "frc4414",
                ],
                "status": {
                    "playoff_average": None,
                    "level": "f",
                    "record": {"losses": 2, "wins": 6, "ties": 1},
                    "status": "won",
                },
            },
        ]
        self.obj_team = [
            {
                "team_number": "1678",
                "matches_played": 5,
                "auto_avg_coral_L1": 0,
                "auto_sd_coral_L1": 0,
                "auto_avg_coral_L2": 0,
                "auto_sd_coral_L2": 0,
                "auto_avg_coral_L3": 0,
                "auto_sd_coral_L3": 0,
                "auto_avg_coral_L4": 0,
                "auto_sd_coral_L4": 0,
                "auto_avg_net": 3,
                "auto_sd_net": 1,
                "auto_avg_processor": 4,
                "auto_sd_processor": 2,
                "tele_avg_net": 2,
                "tele_avg_processor": 2,
                "tele_avg_coral_L1": 1,
                "tele_sd_coral_L1": 0,
                "tele_avg_coral_L2": 1,
                "tele_sd_coral_L2": 0,
                "tele_avg_coral_L3": 1,
                "tele_sd_coral_L3": 0,
                "tele_avg_coral_L4": 1,
                "tele_sd_coral_L4": 0,
                "tele_sd_net": 2,
                "tele_sd_processor": 2,
                "cage_percent_success_all": 1,
                "park_percent": 0.33,
                "endgame_avg_total_points": 5,
                "endgame_sd_total_points": 1.14,
                "climb_after_percent_success": 0,
                "avg_expected_cycles": 1.2332,
                "avg_expected_cycle_time": 3.25,
                "cage_percent_success_deep": 0.9,
                "cage_percent_success_shallow": 0.6,
            },
            {
                "team_number": "254",
                "matches_played": 5,
                "auto_avg_coral_L1": 6,
                "auto_sd_coral_L1": 6,
                "auto_avg_coral_L2": 1,
                "auto_sd_coral_L2": 0,
                "auto_avg_coral_L3": 1,
                "auto_sd_coral_L3": 0,
                "auto_avg_coral_L4": 1,
                "auto_sd_coral_L4": 0,
                "auto_avg_net": 3,
                "auto_sd_net": 1,
                "auto_avg_processor": 4,
                "auto_sd_processor": 2,
                "tele_avg_net": 2,
                "tele_avg_processor": 2,
                "tele_avg_coral_L1": 1,
                "tele_sd_coral_L1": 0,
                "tele_avg_coral_L2": 1,
                "tele_sd_coral_L2": 0,
                "tele_avg_coral_L3": 1,
                "tele_sd_coral_L3": 0,
                "tele_avg_coral_L4": 1,
                "tele_sd_coral_L4": 0,
                "tele_sd_net": 2,
                "tele_sd_processor": 2,
                "cage_percent_success_all": 1,
                "park_percent": 0.33,
                "endgame_avg_total_points": 5,
                "endgame_sd_total_points": 1,
                "climb_after_percent_success": 0,
                "avg_expected_cycles": 1.2332,
                "avg_expected_cycle_time": 3.25,
                "cage_percent_success_deep": 0.9,
                "cage_percent_success_shallow": 0.6,
            },
            {
                "team_number": "4414",
                "matches_played": 5,
                "auto_avg_coral_L1": 2,
                "auto_sd_coral_L1": 2,
                "auto_avg_coral_L2": 2,
                "auto_sd_coral_L2": 0,
                "auto_avg_coral_L3": 1,
                "auto_sd_coral_L3": 0,
                "auto_avg_coral_L4": 3,
                "auto_sd_coral_L4": 0,
                "auto_avg_net": 3,
                "auto_sd_net": 1,
                "auto_avg_processor": 4,
                "auto_sd_processor": 2,
                "tele_avg_net": 2,
                "tele_avg_processor": 2,
                "tele_avg_coral_L1": 1,
                "tele_sd_coral_L1": 0,
                "tele_avg_coral_L2": 1,
                "tele_sd_coral_L2": 0,
                "tele_avg_coral_L3": 1,
                "tele_sd_coral_L3": 0,
                "tele_avg_coral_L4": 1,
                "tele_sd_coral_L4": 0,
                "tele_sd_net": 2,
                "tele_sd_processor": 2,
                "cage_percent_success_all": 1,
                "park_percent": 0.75,
                "endgame_avg_total_points": 5,
                "endgame_sd_total_points": 1.14,
                "climb_after_percent_success": 0.2,
                "avg_expected_cycles": 5,
                "avg_expected_cycle_time": 3.25,
                "cage_percent_success_deep": 0.9,
                "cage_percent_success_shallow": 0.6,
            },
            {
                "team_number": "125",
                "matches_played": 5,
                "auto_avg_coral_L1": 1,
                "auto_sd_coral_L1": 0,
                "auto_avg_coral_L2": 1,
                "auto_sd_coral_L2": 4,
                "auto_avg_coral_L3": 2,
                "auto_sd_coral_L3": 0,
                "auto_avg_coral_L4": 1,
                "auto_sd_coral_L4": 0,
                "auto_avg_net": 3,
                "auto_sd_net": 1,
                "auto_avg_processor": 4,
                "auto_sd_processor": 2,
                "tele_avg_net": 2,
                "tele_avg_processor": 2,
                "tele_avg_coral_L1": 1,
                "tele_sd_coral_L1": 0,
                "tele_avg_coral_L2": 1,
                "tele_sd_coral_L2": 0,
                "tele_avg_coral_L3": 1,
                "tele_sd_coral_L3": 0,
                "tele_avg_coral_L4": 1,
                "tele_sd_coral_L4": 9,
                "tele_sd_net": 2,
                "tele_sd_processor": 2,
                "cage_percent_success_all": 1,
                "park_percent": 1,
                "endgame_avg_total_points": 5,
                "endgame_sd_total_points": 6,
                "climb_after_percent_success": 0,
                "avg_expected_cycles": 1.2332,
                "avg_expected_cycle_time": 3.25,
                "cage_percent_success_deep": 0.9,
                "cage_percent_success_shallow": 0.6,
            },
            {
                "team_number": "5940",
                "matches_played": 5,
                "auto_avg_coral_L1": 1,
                "auto_sd_coral_L1": 4,
                "auto_avg_coral_L2": 1,
                "auto_sd_coral_L2": 10,
                "auto_avg_coral_L3": 1,
                "auto_sd_coral_L3": 0,
                "auto_avg_coral_L4": 1,
                "auto_sd_coral_L4": 0,
                "auto_avg_net": 3,
                "auto_sd_net": 1,
                "auto_avg_processor": 4,
                "auto_sd_processor": 2,
                "tele_avg_net": 2,
                "tele_avg_processor": 2,
                "tele_avg_coral_L1": 1,
                "tele_sd_coral_L1": 0,
                "tele_avg_coral_L2": 1,
                "tele_sd_coral_L2": 0,
                "tele_avg_coral_L3": 1,
                "tele_sd_coral_L3": 0,
                "tele_avg_coral_L4": 1,
                "tele_sd_coral_L4": 0,
                "tele_sd_net": 2,
                "tele_sd_processor": 2,
                "cage_percent_success_all": 1,
                "park_percent": 0,
                "endgame_avg_total_points": 5,
                "endgame_sd_total_points": 1.14,
                "climb_after_percent_success": 0,
                "avg_expected_cycles": 1.2,
                "avg_expected_cycle_time": 3,
                "cage_percent_success_deep": 0.9,
                "cage_percent_success_shallow": 0.6,
            },
            {
                "team_number": "1323",
                "matches_played": 5,
                "auto_avg_coral_L1": 1,
                "auto_sd_coral_L1": 0,
                "auto_avg_coral_L2": 1,
                "auto_sd_coral_L2": 0,
                "auto_avg_coral_L3": 1,
                "auto_sd_coral_L3": 0,
                "auto_avg_coral_L4": 1,
                "auto_sd_coral_L4": 0,
                "auto_avg_net": 1,
                "auto_sd_net": 1,
                "auto_avg_processor": 4,
                "auto_sd_processor": 2,
                "tele_avg_net": 2,
                "tele_avg_processor": 10,
                "tele_avg_coral_L1": 1,
                "tele_sd_coral_L1": 0,
                "tele_avg_coral_L2": 1,
                "tele_sd_coral_L2": 0,
                "tele_avg_coral_L3": 1,
                "tele_sd_coral_L3": 0,
                "tele_avg_coral_L4": 1,
                "tele_sd_coral_L4": 0,
                "tele_sd_net": 1,
                "tele_sd_processor": 2,
                "cage_percent_success_all": 1,
                "park_percent": 1,
                "endgame_avg_total_points": 5,
                "endgame_sd_total_points": 1.14,
                "climb_after_percent_success": 1,
                "avg_expected_cycles": 8,
                "avg_expected_cycle_time": 8,
                "cage_percent_success_deep": 0.9,
                "cage_percent_success_shallow": 0.6,
            },
        ]
        self.tba_team = [
            {
                "team_number": "1678",
                "leave_success_rate": 1,
                "leave_successes": 10,
                "lfm_leave_successes": 4,
                "lfm_spotlight_successes": 0,
                "spotlight_successes": 0,
                "team_name": "Citrus Circuits",
            },
            {
                "team_number": "254",
                "leave_success_rate": 1,
                "leave_successes": 10,
                "lfm_leave_successes": 4,
                "lfm_spotlight_successes": 1,
                "spotlight_successes": 1,
                "team_name": "Cheesy Poofs",
            },
            {
                "team_number": "4414",
                "leave_success_rate": 1,
                "leave_successes": 10,
                "lfm_leave_successes": 4,
                "lfm_spotlight_successes": 0,
                "spotlight_successes": 2,
                "team_name": "High Tide",
            },
            {
                "team_number": "125",
                "leave_success_rate": 1,
                "leave_successes": 10,
                "lfm_leave_successes": 4,
                "lfm_spotlight_successes": 0,
                "spotlight_successes": 0,
                "team_name": "NUTRONs",
            },
            {
                "team_number": "5940",
                "leave_success_rate": 1,
                "leave_successes": 10,
                "lfm_leave_successes": 4,
                "lfm_spotlight_successes": 0,
                "spotlight_successes": 0,
                "team_name": "BREAD",
            },
            {
                "team_number": "1323",
                "leave_success_rate": 1,
                "leave_successes": 10,
                "lfm_leave_successes": 4,
                "lfm_spotlight_successes": 0,
                "spotlight_successes": 1,
                "team_name": "Madtown Robotics",
            },
        ]
        self.tba_match_data = [
            {
                "match_number": 1,
                "comp_level": "sf",
                "key": "2024arc_sf1m1",
                "winning_alliance": "red",
                "score_breakdown": {
                    "red": {
                        "autoPoints": 10,
                        "endGameBargePoints": 24,
                        "teleopPoints": 15,
                        "totalPoints": 49,
                    },
                    "blue": {
                        "autoPoints": 0,
                        "endGameBargePoints": 0,
                        "teleopPoints": 1,
                        "totalPoints": 1,
                    },
                },
            },
        ]
        self.expected_predicted_elims = {
            "1": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 2,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.4100000000000001,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 281.26,
                    "actual_score_auto": 10,
                    "actual_score_endgame": 24,
                    "actual_score_tele": 15,
                    "actual_score": 49,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                    "actual_score_auto": 0,
                    "actual_score_endgame": 0,
                    "actual_score_tele": 1,
                    "actual_score": 1,
                },
                "red_win_chance": 1,
                "alliances": {"R": ["1678", "254", "4414"], "B": ["1323", "125", "4414"]},
            },
            "2": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 273.6,
                },
                "red_win_chance": 0.403,
                "alliances": {"R": ["1678", "125", "5940"], "B": ["1678", "125", "4414"]},
            },
            "3": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 285.88,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "red_win_chance": 0.638,
                "alliances": {"R": ["1323", "125", "5940"], "B": ["1678", "125", "5940"]},
            },
            "4": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 9,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 316.0400000000001,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 293.53999999999996,
                },
                "red_win_chance": 0.646,
                "alliances": {"R": ["1323", "254", "4414"], "B": ["1323", "254", "5940"]},
            },
            "5": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "red_win_chance": 0.739,
                "alliances": {"R": ["1323", "125", "4414"], "B": ["1678", "125", "5940"]},
            },
            "6": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 293.53999999999996,
                },
                "red_win_chance": 0.305,
                "alliances": {"R": ["1678", "125", "5940"], "B": ["1323", "254", "5940"]},
            },
            "7": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 2,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.4100000000000001,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 281.26,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 273.6,
                },
                "red_win_chance": 0.56,
                "alliances": {"R": ["1678", "254", "4414"], "B": ["1678", "125", "4414"]},
            },
            "8": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 285.88,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 9,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 316.0400000000001,
                },
                "red_win_chance": 0.338,
                "alliances": {"R": ["1323", "125", "5940"], "B": ["1323", "254", "4414"]},
            },
            "9": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 273.6,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 293.53999999999996,
                },
                "red_win_chance": 0.383,
                "alliances": {"R": ["1678", "125", "4414"], "B": ["1323", "254", "5940"]},
            },
            "10": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 285.88,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                },
                "red_win_chance": 0.402,
                "alliances": {"R": ["1323", "125", "5940"], "B": ["1323", "125", "4414"]},
            },
            "11": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 2,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.4100000000000001,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 281.26,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 9,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 316.0400000000001,
                },
                "red_win_chance": 0.194,
                "alliances": {"R": ["1678", "254", "4414"], "B": ["1323", "254", "4414"]},
            },
            "12": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 293.53999999999996,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                },
                "red_win_chance": 0.434,
                "alliances": {"R": ["1323", "254", "5940"], "B": ["1323", "125", "4414"]},
            },
            "13": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 2,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.4100000000000001,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 281.26,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                },
                "red_win_chance": 0.34,
                "alliances": {"R": ["1678", "254", "4414"], "B": ["1323", "125", "4414"]},
            },
            "14": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 9,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 316.0400000000001,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                },
                "red_win_chance": 0.561,
                "alliances": {"R": ["1323", "254", "4414"], "B": ["1323", "125", "4414"]},
            },
            "15": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 9,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 316.0400000000001,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                },
                "red_win_chance": 0.561,
                "alliances": {"R": ["1323", "254", "4414"], "B": ["1323", "125", "4414"]},
            },
        }
        self.test_server.local_db.insert_documents("obj_team", self.obj_team)
        self.test_server.local_db.insert_documents("tba_team", self.tba_team)
        with patch("tba_communicator.tba_request", return_value=self.tba_playoffs_data):
            predicted_aim_calc = predicted_aim.PredictedAimCalc(self.test_server)
            self.playoffs_alliances = predicted_aim_calc.get_playoffs_alliances()
            self.test_calc = predicted_elims.PredictedElims(self.test_server)

    def test__init_(self):
        """Test if attributes are set correctly"""
        assert self.test_calc.watched_collections == ["obj_team"]
        assert self.test_calc.server == self.test_server

    def test_predict_match(self):
        expected_result = {
            "R": {
                "_auto_net": 9,
                "_auto_processor": 12,
                "_auto_coral_L1": 8,
                "_auto_coral_L2": 3,
                "_auto_coral_L3": 2,
                "_auto_coral_L4": 4,
                "_auto_leave": 3,
                "_tele_net": 6,
                "_tele_processor": 6,
                "_tele_coral_L1": 3,
                "_tele_coral_L2": 3,
                "_tele_coral_L3": 3,
                "_tele_coral_L4": 3,
                "_endgame_park": 1.4100000000000001,
                "_endgame_shallow": 1.7999999999999998,
                "_endgame_deep": 2.7,
                "predicted_score": 281.26,
                "actual_score_auto": 10,
                "actual_score_endgame": 24,
                "actual_score_tele": 15,
                "actual_score": 49,
            },
            "B": {
                "_auto_net": 7,
                "_auto_processor": 12,
                "_auto_coral_L1": 3,
                "_auto_coral_L2": 3,
                "_auto_coral_L3": 4,
                "_auto_coral_L4": 3,
                "_auto_leave": 3,
                "_tele_net": 6,
                "_tele_processor": 14,
                "_tele_coral_L1": 3,
                "_tele_coral_L2": 3,
                "_tele_coral_L3": 3,
                "_tele_coral_L4": 3,
                "_endgame_park": 2,
                "_endgame_shallow": 1.7999999999999998,
                "_endgame_deep": 2.7,
                "predicted_score": 285.88,
                "actual_score_auto": 0,
                "actual_score_endgame": 0,
                "actual_score_tele": 1,
                "actual_score": 1,
            },
            "red_win_chance": 1,
        }
        assert (
            self.test_calc.predict_match(
                {
                    "R": self.playoffs_alliances[0]["picks"],
                    "B": self.playoffs_alliances[1]["picks"],
                },
                1,
                self.tba_match_data,
            )
            == expected_result
        )

    def test_predict_first_round(self):
        expected_results = {
            "1": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 2,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.4100000000000001,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 281.26,
                    "actual_score_auto": 10,
                    "actual_score_endgame": 24,
                    "actual_score_tele": 15,
                    "actual_score": 49,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                    "actual_score_auto": 0,
                    "actual_score_endgame": 0,
                    "actual_score_tele": 1,
                    "actual_score": 1,
                },
                "red_win_chance": 1,
                "alliances": {"R": ["1678", "254", "4414"], "B": ["1323", "125", "4414"]},
            },
            "2": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 273.6,
                },
                "red_win_chance": 0.403,
                "alliances": {"R": ["1678", "125", "5940"], "B": ["1678", "125", "4414"]},
            },
            "3": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 285.88,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "red_win_chance": 0.638,
                "alliances": {"R": ["1323", "125", "5940"], "B": ["1678", "125", "5940"]},
            },
            "4": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 9,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 316.0400000000001,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 293.53999999999996,
                },
                "red_win_chance": 0.646,
                "alliances": {"R": ["1323", "254", "4414"], "B": ["1323", "254", "5940"]},
            },
        }
        assert self.test_calc.predict_first_round(self.tba_match_data) == expected_results

    def test_predict_future_rounds(self):
        predicted_matches = {
            "1": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 2,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.4100000000000001,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 281.26,
                    "actual_score_auto": 10,
                    "actual_score_endgame": 24,
                    "actual_score_tele": 15,
                    "actual_score": 49,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 4,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.75,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 308.38,
                    "actual_score_auto": 0,
                    "actual_score_endgame": 0,
                    "actual_score_tele": 1,
                    "actual_score": 1,
                },
                "red_win_chance": 1,
                "alliances": {"R": ["1678", "254", "4414"], "B": ["1323", "125", "4414"]},
            },
            "2": {
                "R": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 4,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 273.6,
                },
                "red_win_chance": 0.403,
                "alliances": {"R": ["1678", "125", "5940"], "B": ["1678", "125", "4414"]},
            },
            "3": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 3,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 4,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 285.88,
                },
                "B": {
                    "_auto_net": 9,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 2,
                    "_auto_coral_L2": 2,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 2,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 6,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 251.10000000000002,
                },
                "red_win_chance": 0.638,
                "alliances": {"R": ["1323", "125", "5940"], "B": ["1678", "125", "5940"]},
            },
            "4": {
                "R": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 9,
                    "_auto_coral_L2": 4,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 5,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 2.08,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 316.0400000000001,
                },
                "B": {
                    "_auto_net": 7,
                    "_auto_processor": 12,
                    "_auto_coral_L1": 8,
                    "_auto_coral_L2": 3,
                    "_auto_coral_L3": 3,
                    "_auto_coral_L4": 3,
                    "_auto_leave": 3,
                    "_tele_net": 6,
                    "_tele_processor": 14,
                    "_tele_coral_L1": 3,
                    "_tele_coral_L2": 3,
                    "_tele_coral_L3": 3,
                    "_tele_coral_L4": 3,
                    "_endgame_park": 1.33,
                    "_endgame_shallow": 1.7999999999999998,
                    "_endgame_deep": 2.7,
                    "predicted_score": 293.53999999999996,
                },
                "red_win_chance": 0.646,
                "alliances": {"R": ["1323", "254", "4414"], "B": ["1323", "254", "5940"]},
            },
        }
        assert (
            self.test_calc.predict_future_rounds(predicted_matches, self.tba_match_data)
            == self.expected_predicted_elims
        )

    def test_run(self):
        with patch("tba_communicator.tba_request", return_value=self.tba_match_data):
            self.test_calc.run()
        result = self.test_server.local_db.find("predicted_elims")
        for doc in result:
            match_num = doc["match_number"]
            del doc["match_number"]
            del doc["_id"]
            assert self.expected_predicted_elims[str(match_num)] == doc
