name: lint 

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Run `black`
              uses: psf/black@stable
              with: 
                  options: "--include '.*\\.py' --check -l 100"
                  version: 22.3.0
