name: pytest 

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    pytest:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Install Python Dependencies
              run: python"3.10" -m pip install -r requirements.txt

            - name: Install MongoDB
              run: |
                  sudo apt-get install gnupg curl
                  curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
                    sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
                    --dearmor
                  echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
                  sudo apt-get update
                  sudo apt-get install -y mongodb-org
                  
            - name: Add Competition Code
              run: mkdir data && echo 2025dal > data/competition.txt
            
            - name: Add cloud password
              run: mkdir data/api_keys && echo super_secure_password > data/api_keys/cloud_password.txt
            
            - name: Add Doozer Sigil
              run: echo she_fly_on_my_strawberry_til_i_dashless > data/api_keys/doozernet_key.txt

            - name: Add match schedule and team list
              run: echo "[]" > data/2025dal_match_schedule.json && echo "[]" > data/2025dal_team_list.json
            
            - name: Start mongod
              run: |
                python3 src/start_mongod.py

            # Run pytest with and without always resetting the cloud db to ensure that resetting the Cloud DB only on marked tests does not harm test independence
            - name: Run `pytest`
              run: pytest --verbose

            - name: Run `pytest` and always reset cloud 
              run: pytest --always-reset-cloud --verbose
